[package]
name = "pd-vm-compiler"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
edge = { package = "pd-edge", git = "https://github.com/rustscript-lang/pd-edge.git", rev = "6320847098530ab78b0d3cd438b714e699caa8db" }
vm = { package = "pd-vm", git = "https://github.com/rustscript-lang/rustscript.git", rev = "b1d6cffede77f49410bf63525f30b9a46b02dc01", default-features = false, features = ["runtime"] }
